---
keys:
  - &n2o age195t38wd9auzaduuuljq45tnhdgdy5kez458j9md0u5et76rj4y9sfud4z2
creation_rules:
  - path_regex: secrets/.*\.ya?ml$
    input_type: yaml
    output_type: yaml
    key_groups:
      - age:
          - *n2o
  - path_regex: secrets/gradle\.properties$
    input_type: binary
    output_type: binary
    key_groups:
      - age:
          - *n2o
